### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- fix ynh_npm

### CODE REVIEW

**Comment by ericgaspar** [comment]
-testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
npm run build create a dist folder with files. Not sure it needs a systemd service

**Comment by ericgaspar** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Review by yalh76 — APPROVED** [review]

**Pull request merged**
